// discord.go code
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/discord-go/discord.go/bot"
	"github.com/discord-go/discord.go/components"
	"github.com/discord-go/discord.go/intents"
	"github.com/discord-go/discord.go/interactions"
	"github.com/discord-go/discord.go/messages"
	"github.com/discord-go/discord.go/rest"
	"github.com/discord-go/discord.go/users"
)

func main() {
	token := os.Getenv("DISCORD_TOKEN")
	if token == "" {
		log.Fatal("DISCORD_TOKEN is required")
	}

	router := bot.NewRouter()
	router.Command("v2-components", "Demonstrates Discord Components V2", func(ctx *bot.InteractionContext) {
		botAvatar := "https://cdn.discordapp.com/embed/avatars/0.png"
		if user := ctx.Bot.User(); user != nil {
			botAvatar = user.AvatarURL(users.AvatarURLOptions{Extension: "png", Size: 512})
		}

		text := components.NewTextDisplayBuilder().SetContent("Components V2 example").Build()
		separator := components.NewSeparatorBuilder().SetDivider(true).SetSpacing(components.SeparatorSpacingSmall).Build()
		thumbnail := components.NewThumbnailBuilderWithURL(botAvatar).Build()
		section := components.NewSectionBuilder().
			AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Section title").Build()).
			SetThumbnailAccessory(thumbnail).
			Build()
		selectMenu := components.NewActionRowBuilder().AddComponents(
			components.NewChannelSelectMenuBuilder().SetCustomId("channel_select").SetPlaceholder("Select a channel...").Build(),
		).Build()
		gallery := components.NewMediaGalleryBuilder().AddItemBuilders(
			components.NewMediaGalleryItemBuilderWithURL("https://example.com/image1.png"),
			components.NewMediaGalleryItemBuilderWithURL("https://example.com/image2.png"),
		).Build()
		linkSection := components.NewSectionBuilder().
			AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Discord documentation").Build()).
			SetButtonAccessory(components.NewButtonBuilder().SetLabel("Open docs").SetURL("https://discord.com/developers/docs/components/overview").SetStyle(components.ButtonStyleLink).Build()).
			Build()
		fileComponent := components.NewFileBuilder().SetURL("attachment://embed-export.json").Build()
		container := components.NewContainerBuilder().SetAccentColor(0x5865F2).
			AddMediaGalleryComponents(gallery).
			AddSectionComponents(section, linkSection).
			AddSeparatorComponents(separator).
			AddTextDisplayComponents(text).
			AddFileComponents(fileComponent).
			Build()

		response := &interactions.InteractionCallbackData{
			Flags:      messages.FlagIsComponentsV2,
			Components: []components.Component{text, separator, section, selectMenu, container},
		}
		attachment := rest.NewAttachmentBuilderFromBytes("embed-export.json", []byte(`{"message":"Generated by discord.go Components V2"}`)).Build()
		attachmentPath := os.Getenv("V2_ATTACHMENT")
		if attachmentPath != "" {
			var err error
			attachment, err = rest.FileFromPath(attachmentPath)
			if err != nil {
				_ = ctx.ReplyEphemeral(fmt.Sprintf("Could not load attachment: %v", err))
				return
			}
			attachment.Name = "embed-export.json"
		}
		if err := ctx.ReplyComplexWithFiles(response, attachment); err != nil {
			log.Printf("reply with file: %v", err)
		}
	})

	router.Select("channel_select", func(ctx *bot.InteractionContext) {
		values := ctx.Values()
		if len(values) == 0 {
			_ = ctx.UpdateContent("No channel selected")
			return
		}
		_ = ctx.UpdateContent("Selected channel: " + values[0])
	})

	b := bot.New(token,
		bot.WithIntents(intents.Guilds),
		bot.WithRouter(router),
	)
	b.OnReady(func(ctx *bot.ReadyContext) {
		log.Printf("ready as %s", ctx.User.Username)
	})
	if err := b.Run(); err != nil {
		log.Fatal(err)
	}
}
