// discord.go code
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/discord-go/discord.go/bot"
	"github.com/discord-go/discord.go/components"
	"github.com/discord-go/discord.go/interactions"
	"github.com/discord-go/discord.go/messages"
	"github.com/discord-go/discord.go/permissions"
	"github.com/discord-go/discord.go/rest"
	"github.com/discord-go/discord.go/users"
)

var templateBotPermissions = permissions.ViewChannel | permissions.SendMessages | permissions.EmbedLinks | permissions.ReadMessageHistory

func registerSlashCommands(router *bot.Router, config templateConfig) {
	router.Command("ping", "Check the app latency and status!", func(ctx *bot.InteractionContext) {
		apiLatency, err := ctx.Bot.APILatency(ctx.Context())
		if err != nil {
			log.Printf("ping API check: %v", err)
		}
		content := fmt.Sprintf("# Pong!\n**WebSocket Ping:** %dms\n**API Response Time:** %dms", ctx.Bot.GatewayLatency().Milliseconds(), apiLatency.Milliseconds())
		_ = ctx.ReplyComplex(&interactions.InteractionCallbackData{Flags: messages.FlagIsComponentsV2, Components: []components.Component{templateStatusContainer(config.accentColor(), content)}})
	}).Use(bot.RequireBotPermissions(templateBotPermissions))

	router.Command("text-display", "Shows a TextDisplay component with Markdown.", func(ctx *bot.InteractionContext) {
		text := components.NewTextDisplayBuilder().SetContent("This is a TextDisplay component.\nSupports Markdown formatting.").Build()
		separator := components.NewSeparatorBuilder().SetDivider(true).Build()
		container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddTextDisplayComponents(text).AddSeparatorComponents(separator).Build()
		_ = replyV2(ctx, container)
	})

	router.Command("file-component", "Demonstrates attaching a file dynamically using Components V2", func(ctx *bot.InteractionContext) {
		data, _ := json.MarshalIndent(map[string]interface{}{"message": "Hello from Components V2!", "timestamp": "generated by discord.go"}, "", "  ")
		attachment := rest.NewAttachmentBuilderFromBytes("dummy.json", data).Build()
		file := components.NewFileBuilder().SetURL("attachment://dummy.json").Build()
		text := components.NewTextDisplayBuilder().SetContent("File Component Example\nThis JSON file is attached dynamically.").Build()
		container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddTextDisplayComponents(text).AddFileComponents(file).Build()
		_ = ctx.ReplyComplexWithFiles(&interactions.InteractionCallbackData{Flags: messages.FlagIsComponentsV2, Components: []components.Component{container}}, attachment)
	})

	router.Command("v2-components", "Sends a message demonstrating all Components V2", func(ctx *bot.InteractionContext) {
		_ = ctx.ReplyComplexWithFiles(v2ComponentsPayload(ctx, config), rest.NewAttachmentBuilderFromBytes("dummy.json", []byte(`{"message":"This is a dummy JSON file"}`)).Build())
	})

	router.Command("separator", "Shows supported V2 component separators.", func(ctx *bot.InteractionContext) {
		container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).
			AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Small Divider").Build()).
			AddSeparatorComponents(components.NewSeparatorBuilder().SetDivider(true).SetSpacing(components.SeparatorSpacingSmall).Build()).
			AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Large Divider").Build()).
			AddSeparatorComponents(components.NewSeparatorBuilder().SetDivider(true).SetSpacing(components.SeparatorSpacingLarge).Build()).
			AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Invisible Spacer").Build()).
			AddSeparatorComponents(components.NewSeparatorBuilder().SetDivider(false).SetSpacing(components.SeparatorSpacingSmall).Build()).
			Build()
		_ = replyV2(ctx, container)
	})

	router.Command("button-1", "Shows a link button (style 1)", func(ctx *bot.InteractionContext) {
		button := components.NewButtonBuilder().SetLabel("Support").SetURL("https://discord.gg/6YVmxA4Qsf").SetStyle(components.ButtonStyleLink).Build()
		section := components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Click the button to join support").Build()).SetButtonAccessory(button).Build()
		_ = replyV2(ctx, components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddSectionComponents(section).Build())
	})

	router.Command("button-2", "Shows a link button inside a container (style 2)", func(ctx *bot.InteractionContext) {
		row := components.NewActionRowBuilder().AddComponents(components.NewButtonBuilder().SetLabel("Visit ZarScape Site").SetStyle(components.ButtonStyleLink).SetURL("https://zarScape.github.io").Build()).Build()
		container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Click the button below to visit my site:").Build()).AddSeparatorComponents(components.NewSeparatorBuilder().SetDivider(true).SetSpacing(components.SeparatorSpacingSmall).Build()).AddActionRowComponents(row).Build()
		_ = replyV2(ctx, container)
	})

	router.Command("button-3", "Demonstrates a report-style button (external link).", func(ctx *bot.InteractionContext) {
		row := components.NewActionRowBuilder().AddComponents(components.NewButtonBuilder().SetLabel("Join Our Support Server").SetStyle(components.ButtonStyleLink).SetURL("https://discord.gg/6YVmxA4Qsf").Build()).Build()
		container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Click below to report an issue.").Build()).Build()
		_ = ctx.ReplyComplex(&interactions.InteractionCallbackData{Flags: messages.FlagIsComponentsV2, Components: []components.Component{container, row}})
	})

	router.Command("section-and-thumbnail", "Shows a Section component with optional thumbnail.", func(ctx *bot.InteractionContext) {
		avatar := "https://cdn.discordapp.com/embed/avatars/0.png"
		if user := ctx.Bot.User(); user != nil {
			avatar = user.AvatarURL(users.AvatarURLOptions{Extension: "png", Size: 512})
		}
		section := components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Section Title").Build(), components.NewTextDisplayBuilder().SetContent("This is a section description with a thumbnail.").Build()).SetThumbnailAccessory(components.NewThumbnailBuilderWithURL(avatar).Build()).Build()
		_ = replyV2(ctx, components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddSectionComponents(section).Build())
	})

	router.Command("media-gallery", "Displays a carousel of images using MediaGallery.", func(ctx *bot.InteractionContext) {
		gallery := components.NewMediaGalleryBuilder().AddItems(components.NewMediaGalleryItemBuilderWithURL(templateImageURL)).Build()
		_ = replyV2(ctx, components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddMediaGalleryComponents(gallery).Build())
	})

	router.Command("menu", "Demonstrates multiple select menu types", func(ctx *bot.InteractionContext) {
		selected := ctx.GetStringOption("type")
		var menu components.Component
		switch selected {
		case "channel":
			menu = components.NewChannelSelectMenuBuilder().SetCustomId("menu_channel").SetPlaceholder("Select a channel").SetChannelTypes(0, 2, 4, 5, 13).Build()
		case "role":
			menu = components.NewRoleSelectMenuBuilder().SetCustomId("menu_role").SetPlaceholder("Select a role").Build()
		case "string":
			menu = components.NewStringSelectMenuBuilder().SetCustomId("menu_string").SetPlaceholder("Select an option").AddOptions(
				components.NewSelectOptionBuilder().SetLabel("Option 1").SetValue("option1"),
				components.NewSelectOptionBuilder().SetLabel("Option 2").SetValue("option2"),
				components.NewSelectOptionBuilder().SetLabel("Option 3").SetValue("option3"),
			).Build()
		case "user":
			menu = components.NewUserSelectMenuBuilder().SetCustomId("menu_user").SetPlaceholder("Select a user").Build()
		default:
			_ = ctx.ReplyEphemeral("Unknown menu type!")
			return
		}
		row := components.NewActionRowBuilder().AddComponents(menu).Build()
		container := components.NewContainerBuilder().SetAccentColor(0x5865F2).AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("You selected **" + selected + "** menu type.").Build()).AddActionRowComponents(row).Build()
		_ = replyV2(ctx, container)
	}, interactions.ApplicationCommandOption{Type: interactions.ApplicationCommandOptionTypeString, Name: "type", Description: "Select a menu type", Required: true, Choices: []interactions.ApplicationCommandOptionChoice{{Name: "Channel", Value: "channel"}, {Name: "Role", Value: "role"}, {Name: "String", Value: "string"}, {Name: "User", Value: "user"}}})
}

const templateImageURL = "https://raw.githubusercontent.com/ZarScape/ZarScape/refs/heads/main/images/ZarScape/logo-with-background.png"

func replyV2(ctx *bot.InteractionContext, componentsValue components.Component) error {
	return ctx.ReplyComplex(&interactions.InteractionCallbackData{Flags: messages.FlagIsComponentsV2, Components: []components.Component{componentsValue}})
}

func templateStatusContainer(color int, content string) components.Container {
	separator := components.NewSeparatorBuilder().Build()
	return components.NewContainerBuilder().SetAccentColor(color).AddSeparatorComponents(separator).AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent(content).Build()).AddSeparatorComponents(separator).Build()
}

func v2ComponentsPayload(ctx *bot.InteractionContext, config templateConfig) *interactions.InteractionCallbackData {
	avatar := "https://cdn.discordapp.com/embed/avatars/0.png"
	if user := ctx.Bot.User(); user != nil {
		avatar = user.AvatarURL(users.AvatarURLOptions{Extension: "png", Size: 512})
	}
	text := components.NewTextDisplayBuilder().SetContent("This is a TextDisplay component.").Build()
	separator := components.NewSeparatorBuilder().SetDivider(true).SetSpacing(components.SeparatorSpacingSmall).Build()
	section := components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Section Title").Build(), components.NewTextDisplayBuilder().SetContent("This is a description inside a Section component, with a thumbnail.").Build()).SetThumbnailAccessory(components.NewThumbnailBuilderWithURL(avatar).Build()).Build()
	selectRow := components.NewActionRowBuilder().AddComponents(components.NewChannelSelectMenuBuilder().SetCustomId("channel_select_menu").SetPlaceholder("Select a channel...").Build()).Build()
	gallery := components.NewMediaGalleryBuilder().AddItems(components.NewMediaGalleryItemBuilderWithURL(templateImageURL), components.NewMediaGalleryItemBuilderWithURL(templateImageURL)).Build()
	sections := []components.Component{
		components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("GitHub").Build()).SetButtonAccessory(components.NewButtonBuilder().SetLabel("GitHub").SetURL("https://github.com/ZarScape").SetStyle(components.ButtonStyleLink).Build()).Build(),
		components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("YouTube").Build()).SetButtonAccessory(components.NewButtonBuilder().SetLabel("Channel").SetURL("https://www.youtube.com/@ZarScape").SetStyle(components.ButtonStyleLink).Build()).Build(),
		components.NewSectionBuilder().AddTextDisplayComponents(components.NewTextDisplayBuilder().SetContent("Discord").Build()).SetButtonAccessory(components.NewButtonBuilder().SetLabel("Zar HQ").SetURL("https://discord.gg/6YVmxA4Qsf").SetStyle(components.ButtonStyleLink).Build()).Build(),
	}
	container := components.NewContainerBuilder().SetAccentColor(config.accentColor()).AddMediaGalleryComponents(gallery).AddSectionComponents(section).AddMediaGalleryComponents(components.NewMediaGalleryBuilder().AddItems(components.NewMediaGalleryItemBuilderWithURL(avatar)).Build()).AddSectionComponents(sections...).AddSeparatorComponents(separator).AddTextDisplayComponents(text).AddFileComponents(components.NewFileBuilder().SetURL("attachment://dummy.json").Build()).Build()
	return &interactions.InteractionCallbackData{Flags: messages.FlagIsComponentsV2, Components: []components.Component{text, separator, section, selectRow, container}}
}
